# Generated by Django 5.0.4 on 2024-04-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catNom', models.CharField(max_length=50)),
                ('catDescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaNom', models.CharField(max_length=50)),
                ('marcaDescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidosnumtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidoUser', models.CharField(max_length=50)),
                ('pedidoIdUser', models.IntegerField()),
                ('pedidoFecha', models.DateTimeField(auto_now_add=True)),
                ('pedidoCodigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilValor', models.FloatField()),
                ('utilDescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidostest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('acumulado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.pedidosnumtest')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('precioCosto', models.FloatField(default=0.0)),
                ('precioPublico', models.FloatField(default=0.0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categorias')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.marcas')),
                ('utilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.utilidad')),
            ],
        ),
    ]
