# Generated by Django 5.0.1 on 2024-01-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catNom', models.CharField(max_length=50)),
                ('catDescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('ultimoIngreso', models.DateTimeField(auto_now_add=True)),
                ('precioCosto', models.FloatField()),
                ('utilidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilValor', models.FloatField()),
                ('utilDescripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
