# Generated by Django 5.0.1 on 2024-04-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_pedidosnumtest_pedidototal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivaValor', models.FloatField()),
                ('ivaDescripcion', models.CharField(max_length=10)),
            ],
        ),
    ]
