# Generated by Django 5.0.1 on 2024-01-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioPublico',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioCosto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='utilidad',
            field=models.FloatField(default=0.0),
        ),
    ]
