# Generated by Django 5.0.1 on 2024-01-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_producto_preciopublico_alter_producto_preciocosto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ultimoIngreso',
        ),
    ]
