# Generated by Django 5.0.1 on 2024-04-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iva',
            name='ivaValor',
            field=models.FloatField(default=0.0),
        ),
    ]
