# Generated by Django 5.0.1 on 2024-04-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_iva_ivavalor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.iva'),
        ),
    ]
