# Generated by Django 5.0.1 on 2024-01-11 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_producto_ultimoingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ultimoIngreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
