# Generated by Django 5.0.1 on 2024-01-16 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_producto_ultimoingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaNom', models.CharField(max_length=50)),
                ('marcaDescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='utilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.utilidad'),
        ),
        migrations.AlterField(
            model_name='utilidad',
            name='utilDescripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.marca'),
        ),
    ]
