# Generated by Django 5.0.1 on 2024-01-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_marca_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Marca',
            new_name='Marcas',
        ),
    ]
