# Generated by Django 5.0.1 on 2024-01-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_rename_categoria_categorias_rename_marca_marcas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ultimoIngreso',
        ),
    ]
