# Generated by Django 5.0.3 on 2024-03-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_pedidos_productopedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidostest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('id_usuario', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('acumulado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
