# Generated by Django 5.0.2 on 2024-03-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_pedidostest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidosnumtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidoNum', models.IntegerField(auto_created=True, default=0)),
                ('pedidoUser', models.CharField(max_length=50)),
                ('pedidoIdUser', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidostest',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='pedidostest',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedidostest',
            name='numPedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stock.pedidosnumtest'),
        ),
    ]
