# Generated by Django 5.0.2 on 2024-03-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_pedidosnumtest_remove_pedidostest_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidostest',
            name='numPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.pedidosnumtest'),
        ),
    ]
