# Generated by Django 5.0.3 on 2024-03-31 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_pedidosnumtest_pedidofecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosnumtest',
            name='pedidoCodigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
