# Generated by Django 5.0.3 on 2024-04-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_pedidosnumtest_pedidocodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosnumtest',
            name='pedidoCodigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
