# Generated by Django 5.0.3 on 2024-04-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_pedidosnumtest_pedidocodigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosnumtest',
            name='pedidoNum',
        ),
    ]
