# Generated by Django 5.0.3 on 2024-04-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_remove_pedidosnumtest_pedidonum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopedido',
            name='numpedido',
        ),
        migrations.RemoveField(
            model_name='productopedido',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='productopedido',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Productopedido',
        ),
    ]
