version: "3.8"

services:
  app:
    image: waferapp:v0.5
    restart: always
    ports:
      - '8002:8002'
    volumes:
      - .:/app
      - static:/app/static
  mysql:
    image: mysql:8.0.36-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: atleticotucuman
      MYSQL_DATABASE: wafersas
      MYSQL_USER: waferuser
      MYSQL_PASSWORD: Coni1734
    ports:
      - '3306:3306'
    expose:
    # Abrir puerto  3306 en el contenedor
    - '3306'
    volumes:
    # Donde los datos quedan persistentes
      - wafer_db:/var/lib/mysql
  nginx:
    image: nginx:1.25.4-alpine
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/static
    depends_on:
      - app
      - mysql

# Nombre de los Volumes
volumes:
  wafer_db:
  static:

#gunicorn --bind 0.0.0.0:8003 buloneria.wsgi
