INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (3,'BULONERIA','TORNILLO CABEZA HEXAGONAL M12X45',8,560,510,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (4,'BULONERIA','TORNILLO FIX 6X55',23,32.45,34.12,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (5,'BULONERIA','TORNILLO FIX 5X45',34,23,23,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (6,'BULONERIA','TUERCA M10 DUREZA 8',560,26,28,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (7,'BULONERIA','ARANDELA M6X20MM',789,12,15,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (8,'BULONERIA','TORNILLO ALLEN M4X50 CABEZA CILINDRICA',343,100,110,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (9,'BULONERIA','TORNILLO ALLEN M6X35 CABEZA CILINDRICA',234,76,78,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (10,'BULONERIA','ARANDELA DE PRESION 1/4" -',500,13,15,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (11,'BULONERIA','ARANDELA GROOVER 5/8"',400,21,24,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (12,'BULONERIA','TORNILLO ALLEN CABEZA FRESASA M8X40',50,100,105,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (1,'BULONERIA','TORNILLO PARKER 3MM PHILIPS',2323,12,14,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (13,'BULONERIA','TORNILLO FIX 4.5X40',400,20,23,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (14,'BULONERIA','TUERCA AUTOFRENANTE M8 ZINCADA',435,25,26,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (15,'BULONERIA','TUERCA AUTOFRENANTE M6 ZINCADA',564,20,23,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (16,'BULONERIA','TORNILLO CABEZA HEXAGONAL 3/8 WHITWORTH',120,15,16,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (17,'BULONERIA','TORNILLO CABEZA HEXAGONAL 5/16 WHITWORTH',300,14,15,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (18,'BULONERIA','ARANDELA BISELADA M8 ZINC',369,20,24,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (235,'FERRETERIA','LIMA BASTARDA 10 PULGADAS',25,2500,2950,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (34342,'BULONERIA','TORNILLO PRISIONERO M6',333,34,50,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (4586,'FERRETERIA','LLAVE COMBINADA N19',45,2000,2500,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (6985,'FERRETERIA','LLAVE COMBINADA N13',10,1900,2400,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (232424,'FERRETERIA','LLAVE COMBINADA N12',23,1300,1500,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (45332,'FERRETERIA','LLAVE FRANCESA 10 PULGADAS',234,2300,3000.43,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (4585,'FERRETERIA','CALIBRE ANALOGICO ACERO INOX 150MM',12,19000,25500,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (8998,'FERRETERIA','DESTORNILLADOR PLANO 4X150MM',15,1500,1720.6,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (9854,'FERRETERIA','BASE MAGNETIA ARTICULADA 300M',2,35000,42562.36,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (658,'FERRETERIA','DESTORNILLADOR PH1X150MM',12,1000,1253,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (45875,'FERRETERIA','MECHA ACERO RAPIDO 2MM',10,450,510,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (45869,'FERRETERIA','MECHA ACERO RAPIDO 4MM',10,560,595,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (6958,'FERRETERIA','FRESA AVELLANADORA M6 ENCASTRE 1/4',50,3500,4002,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (7485,'FERRETERIA','TUBO ESTRIADO METRICO 15 1/2',15,1400,1745,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (9658,'FERRETERIA','NIVEL LASER 15M ALCANCE EJE X/Y',2,56000,62355.14,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (69658,'FERRETERIA','TORNILLO MICROMETRICO 25-50MM',2,45752.36,55000,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (7563,'FERRETERIA','REGLA METALICA DE 300 MM',11,740,955.5,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (324,'FERRETERIA','ESCUADRA MAGNETICA DE 3 PULGADAS',7,2500,2945,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (236,'FERRETERIA','LIMA BASTARDA 8 PULGADAS',25,2500,2950,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (45876,'FERRETERIA','MECHA ACERO RAPIDO 8MM',10,942,1050,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (45880,'FERRETERIA','MECHA ACERO RAPIDO 10MM',11,1200,1350,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (85648,'FERRETERIA','PINZA UNIVERSAL 8 PULGADAS',16,1500,1600.25,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (56537,'FERRETERIA','PRENSA "G" 4 PULGADAS',3,3000,4000,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (34343,'BULONERIA','TORNILLO PRISIONERO M8',333,35,55,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (45881,'FERRETERIA','MECHA ACERO RAPIDO 10.5MM',13,1250,1400,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (34344,'BULONERIA','TORNILLO PRISIONERO M10',100,50,65,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (45878,'FERRETERIA','MECHA ACERO RAPIDO 6MM',12,1250,1450,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (345345,'FERRETERIA','LLAVE PICO DE LORO 6 PLGADAS',4,3000,3500,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (2,'BULONERIA','TORNILLO FIX 5X55MM',100,23,25,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (999,'BULONERIA','stock_PRODUCTO',990,2,2,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (1234567,'BULONERIA','TORNILLO FIX 3X16MM',200,12,15,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (1234565,'FERRETERIA','LLAVE INGLESA DE 10 PULGADAS',4,2500,3000,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (23,'FERRETERIA','PINZA DE PUNTA RECTA 6 PULGADAS',2,5500,7000,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (24,'FERRETERIA','PINZA CRIMPEADORA TERMINALES TIFF 0-16MM',2,20000,24570,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (25,'BULONERIA','TUERCA M8 DUREZA 8',200,12,15,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (26,'FERRETERIA','JUEGO DE LLAVES ALLEN MILIMETRICAS',2,10000,12000,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (22,'BULONERIA','TUERCA CASTILLO M10',92,50,60,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (25642,'FERRETERIA','ARCO DE SIERRA',2,5000,6000,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (35426,'FERRETERIA','ESCUADRA CON SOMBRERO 150MM NORMA DIN',1,7500,8365.4,'',0);
INSERT INTO stock_producto (codigo,categoria,descripcion,cantidad,precioCosto,precioPublico,marca,utilidad) VALUES (2323,'FERRETERIA','PUNTA DE TRZAR DE WIDIA',10,1200,1450,'',0);