"""
Django settings for buloneria project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u@1gp*4jph!n^^hci9rxq@ls92ho*unxt)5me^x7^b00$2a$1&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#####EN TEST##################

ALLOWED_HOSTS = ['*']


####EN PRODUCCION###############################
#ALLOWED_HOSTS = ['djangobuloneriapedidos-production.up.railway.app','127.0.0.1']

#CSRF_TRUSTED_ORIGINS  = [
#    "https://djangobuloneriapedidos-production.up.railway.app",
    # Otros orígenes permitidos si es necesario
#]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stock',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'buloneria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stock.context_processor.total_carrito',
            ],
    
        },
    },
]

WSGI_APPLICATION = 'buloneria.wsgi.application'
####PARA DESPLEGAR EN DOCKER 
##CSRF_TRUSTED_ORIGINS = ["186.123.87.15", "https://waferserver.ddns.net", "https://www.waferserver.ddns.net"]


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

###############POSTGRES LOCALHOST#######################
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'wafersas',
        'USER': 'postgres',
        'PASSWORD': '12345678',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}'''

###############BASE LOCAL MYSQL PARA DOCKER EN PRODUCCION##################
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wafersas',
        'USER': 'waferuser',
        'PASSWORD': 'Coni1734',
        'HOST': 'mysql',
        'PORT': '3306'
    }
}'''
##########BASE MYSQL HOSTINGER#################
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'u653598207_wafersas',
        'USER': 'u653598207_root',
        'PASSWORD': 'Buloneria123456',
        'HOST': '154.49.247.154',
        'PORT': '3306'
    }
}'''

######### BASE DE DATOS PARA DESARROLLO#########
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

#####
STATIC_URL = 'stock/static/'
LOGIN_URL = 'signin'
STATIC_ROOT = 'static/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'